# docker-compose.yml
version: '3.8'

services:
  app:
    build: ./backend
    environment:
      - MONGODB_URI=mongodb://mongo:27017/confession
      - JWT_SECRET=${JWT_SECRET}
    depends_on:
      - mongo
    networks:
      - chapel-net

  mongo:
    image: mongo:6.0
    volumes:
      - mongo-data:/data/db
    networks:
      - chapel-net

  nginx:
    image: nginx:1.25-alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./frontend/build:/usr/share/nginx/html
      - ./nginx:/etc/nginx/conf.d
    depends_on:
      - app
    networks:
      - chapel-net

volumes:
  mongo-data:

networks:
  chapel-net: